# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [4]:
import numpy as np

In [5]:
w = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(w)

v = np.arange(1, 11)
print(v)


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [7]:
c = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
print(c)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [9]:
a = np.linspace(0,5,10, endpoint= False)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [11]:
c = np.identity(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [14]:
d = np.random.rand(4, 4)
print(d)

[[0.58189095 0.19949889 0.27761319 0.81369232]
 [0.18937838 0.00233297 0.13560153 0.14625825]
 [0.65751474 0.72806143 0.25829423 0.96927809]
 [0.09898411 0.77096455 0.2642144  0.50411287]]


### Exercise 6:
Find the shape of a NumPy array.

In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])
shape = array.shape
print(shape)

(2, 3)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [18]:
ar = np.arange(1, 17)
mat = ar.reshape(4, 4)
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

In [20]:
array = np.array([1, 2, 3, 4])
data_type = array.dtype
print(data_type)

int64


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [22]:
arr = np.arange(1, 100)
o = [i for i in arr if i % 2 == 0]
print(o)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [24]:
q = np.random.randint(10, 50, (6, 6))
q

array([[13, 27, 49, 16, 46, 40],
       [49, 36, 37, 21, 11, 49],
       [33, 13, 11, 49, 28, 42],
       [41, 30, 45, 17, 12, 46],
       [49, 31, 16, 38, 35, 49],
       [46, 25, 42, 16, 19, 47]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [26]:
d = np.array([[2, 3, 4], [4, 6, 7]])

# Obtenir la première ligne
premiere_ligne = d[0]
n1 = d[:, 0]
n2 = d[:, 1]
g = np.array([n1, n2])
# Obtenir un élément spécifique (ligne 1, colonne 2)
element = d[1, 2]

# Afficher les résultats
print("Tableau d :")
print(d)
print(g)
print("Élément (ligne 1, colonne 2) :", element)

Tableau d :
[[2 3 4]
 [4 6 7]]
[[2 4]
 [3 6]]
Élément (ligne 1, colonne 2) : 7


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [28]:
m = np.random.randint(8, 10, (6, 8))
print(m)
l = np.sum(m, axis=0)
l

[[8 8 9 8 9 9 9 8]
 [8 9 8 8 9 8 8 8]
 [9 9 9 8 8 9 8 8]
 [8 9 8 8 9 9 8 9]
 [9 9 9 8 8 8 9 9]
 [9 8 9 9 8 8 8 8]]


array([51, 52, 52, 49, 51, 51, 50, 50])

In [29]:
help(np.sum)

Help on _ArrayFunctionDispatcher in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.

    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.

        .. versionadded:: 1.7.0

        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [31]:
d = np.identity(9)
print(d)
m1 = np.mean(d, axis= 0)
m2 = np.median(d, axis = 0)
m3 = np.std(d, axis = 0)
print(m1, m2, m3)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
 0.11111111 0.11111111 0.11111111] [0. 0. 0. 0. 0. 0. 0. 0. 0.] [0.31426968 0.31426968 0.31426968 0.31426968 0.31426968 0.31426968
 0.31426968 0.31426968 0.31426968]


In [32]:
help(np.mean )

Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [34]:
v = np.random.randint(15, 31, (6, 5))
v1 = np.max(v)
v2 = np.min(v)
v3 = np.max(v, axis = 0)
v4 = np.min(v, axis = 1)
print(v)
print(v1)
print(v2)
print(v3)
print(v4)


[[27 26 27 26 26]
 [29 20 16 30 30]
 [28 20 22 17 28]
 [25 19 23 24 17]
 [29 27 26 28 27]
 [25 27 27 20 17]]
30
16
[29 27 27 30 30]
[26 16 17 17 26 17]


In [35]:
help(np.max)

Help on _ArrayFunctionDispatcher in module numpy:

max(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the maximum of an array or maximum along an axis.

    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, the maximum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See :ref:`ufuncs-output-type` for more details.

    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will 

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [37]:
array = np.random.randint(0, 100, 20)
index_max = np.argmax(array)

print(array)
print(index_max)
print(array[index_max])

[46 45 16  8 27 79  2 44 92 66 84 78 88 12 88 72 18 29 69 22]
8
92


### Exercise 16:
Create a NumPy array and reverse its elements.


In [39]:
import numpy as np

array = np.random.randint(0, 100, 20)
f = array[::-1]

print(array)
print(f)


[39  2  6  5 12 40 90 86 33 76 45 91 82 82 63 31 37  1 21 73]
[73 21  1 37 31 63 82 82 91 45 76 33 86 90 40 12  5  6  2 39]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [41]:
arr1 = np.random.randint(0, 6, (3,3))
arr2 = np.random.randint(0, 12, (3,3))
print(arr1)
print(arr2)
prod = np.multiply(arr1, arr2)
print(prod)

[[4 1 0]
 [3 4 0]
 [2 3 2]]
[[2 8 9]
 [2 7 1]
 [4 1 0]]
[[ 8  8  0]
 [ 6 28  0]
 [ 8  3  0]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [43]:
m = np.arange(1, 11)
l = np.diag(m)
print(l)


[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [45]:
import numpy as np

ar1 = np.array([[1, 2, 3, 4, 5, 6], [0, 3, 4, 7, 18, 40]])
ar2 = np.array([[1, 2, 3, 9, 5, 19], [0, 3, 84, 7, 18, 21]])

# Multiplication of two matrix with np.dot()
m = np.dot(ar1, ar2.T) 
print("ar1:\n", ar1)
print("ar2:\n", ar2)
print("Multiplication de matrices:\n", m)

ar1:
 [[ 1  2  3  4  5  6]
 [ 0  3  4  7 18 40]]
ar2:
 [[ 1  2  3  9  5 19]
 [ 0  3 84  7 18 21]]
Multiplication de matrices:
 [[ 189  502]
 [ 931 1558]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [47]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_1d = array_2d.flatten()
print(array_1d)

[1 2 3 4 5 6 7 8 9]


### Exercise 21:
Stack two NumPy arrays vertically.

In [49]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_array1 = np.vstack((a1, a2))
print(stacked_array1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Exercise 22:
Stack two NumPy arrays horizontally.

In [51]:
stacked_array2 = np.hstack((a1, a2))
print(stacked_array2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [53]:
#Create a NumPy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Split the array into 3 equal sub-arrays
sub_arrays = np.split(array, 3)
# Display the sub-arrays
for i, arr in enumerate(sub_arrays):
    print(f"Sub-array {i + 1}: {arr}")

Sub-array 1: [1 2 3]
Sub-array 2: [4 5 6]
Sub-array 3: [7 8 9]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [55]:
# Generate a random array with values between 0 and 1
rd_array = np.random.rand(5, 5)
# Round each element to two decimal places
rounded_array = np.round(rd_array, 2)
print("Original Array:\n", rd_array)
print("\nRounded Array:\n", rounded_array)

Original Array:
 [[0.73561077 0.5125312  0.81033811 0.51603725 0.35442123]
 [0.75661245 0.33081112 0.05921615 0.02071656 0.47481989]
 [0.70835143 0.79267696 0.99640218 0.11346215 0.19273652]
 [0.43232725 0.25932002 0.38769443 0.04291839 0.51796699]
 [0.28480109 0.29987945 0.3091117  0.29380211 0.10687682]]

Rounded Array:
 [[0.74 0.51 0.81 0.52 0.35]
 [0.76 0.33 0.06 0.02 0.47]
 [0.71 0.79 1.   0.11 0.19]
 [0.43 0.26 0.39 0.04 0.52]
 [0.28 0.3  0.31 0.29 0.11]]


### Exercise 25:
Find the unique elements of a NumPy array.

In [57]:
import numpy as np# Create a NumPy array
array = np.array([1, 2, 3, 4, 3, 2, 1, 5, 6, 5])
# Find the unique elements in the array
unique_elements = np.unique(array)
print("Original Array:", array)
print("Unique Elements:", unique_elements)

Original Array: [1 2 3 4 3 2 1 5 6 5]
Unique Elements: [1 2 3 4 5 6]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---